copyright: Apache License v2.0
description: Shared components for Hue
name: ccs-shared
sources: [
  Source/JFrameFilters/CCS.JFrame.FormRequest.js,
  Source/JFrameFilters/CCS.JFrame.Clearfix.js,
  Source/JFrameFilters/CCS.JFrame.AutoRefresh.js,
  Source/JFrameFilters/CCS.JFrame.DoubleClickDelegate.js,
  Source/JFrameFilters/CCS.JFrame.ToggleHistory.js,
  Source/JFrameFilters/CCS.JFrame.Deprecated.js,
  Source/Fx/Fx.Shake.js,
  Source/JFrameRenderers/CCS.JFrame.Alert.js,
  Source/JFrameRenderers/CCS.JFrame.Prompt.js,
  Source/JFrameRenderers/CCS.JFrame.PartialRefresh.js,
  Source/CCS/CCS.ContextMenu.js,
  Source/CCS/CCS.js,
  Source/CCS/CCS.JBrowser.js,
  Source/CCS/CCS.Error.js,
  Source/CCS/CCS.JFrame.js,
  Source/CCS/CCS.Request.js,
  Source/CCS/CCS.SideScroller.js,
  Source/CCS/CCS.SolidWindow.js,
  Source/CCS/CCS.DropDown.js,
  Source/CCS/CCS.Desktop.js,
  Source/CCS/CCS.Desktop.FlashMessage.js,
  Source/CCS/CCS.Desktop.Config.js,
  Source/CCS/CCS.Dock.js,
  Source/CCS/CCS.Desktop.Keys.js,
  Source/CCS/CCS.User.js,
  Source/CCS/CCS.Login.js,
  Source/Forms/Form.Request.JSON.js,
  Source/Forms/EditInline.js,
  Source/UI/StickyWin.Drawer.js,
  Source/UI/StickyWin.UI.Solid.js,
  Source/UI/ThumbTack.js,
  Source/JFrameLinkers/CCS.JFrame.AjaxLoad.js,
  Source/JFrameLinkers/CCS.JFrame.CheckAllOrNone.js,
  Source/JFrameLinkers/CCS.JFrame.Chooser.js,
  Source/JFrameLinkers/CCS.JFrame.ConfirmAndPost.js,
  Source/JFrameLinkers/CCS.JFrame.FakeRefresh.js,
  Source/JFrameLinkers/CCS.JFrame.Nav.js,
  Source/JFrameLinkers/CCS.JFrame.NoScroll.js,
  Source/JFrameLinkers/CCS.JFrame.PromptAndPost.js,
  Source/JFrameLinkers/CCS.JFrame.Refresh.js,
  Source/JFrameLinkers/CCS.JFrame.SubmitLink.js,
  Source/JFrameLinkers/CCS.JFrame.Target.js,
  Source/Native/String.CCS.js,
  Source/Native/Element.Data.js,
  Source/StaticThirdParty/DynamicTextarea.js,
  Source/CCS/CCS.PostEditor.Simple.js,
  Source/UI/ART.SideBySideSelect.js,
  Source/BehaviorFilters/Behavior.CollapsingElements.js,
  Source/BehaviorFilters/Behavior.ContextMenu.js,
  Source/BehaviorFilters/Behavior.DataGroupToggle.js,
  Source/BehaviorFilters/Behavior.FilterInput.js,
  Source/BehaviorFilters/Behavior.FitText.js,
  Source/BehaviorFilters/Behavior.HtmlTableCheckSelected.js,
  Source/BehaviorFilters/Behavior.HtmlTableChromeHack.js,
  Source/BehaviorFilters/Behavior.HtmlTableKeyboard.js,
  Source/BehaviorFilters/Behavior.HtmlTableMultiSelectMenu.js,
  Source/BehaviorFilters/Behavior.MultiChecks.js,
  Source/BehaviorFilters/Behavior.PostEditor.js,
  Source/BehaviorFilters/Behavior.SelectWithOther.js,
  Source/BehaviorFilters/Behavior.SideBySideSelect.js,
  Source/BehaviorFilters/Behavior.SizeTo.js,
  Source/BehaviorFilters/Behavior.SplitViewPostFold.js,
  Source/BehaviorFilters/Behavior.SplitViewScroller.js,
  Source/BehaviorFilters/Behavior.SubmitOnChange.js,
  Source/BehaviorFilters/Behavior.Tabs.js,
  Source/BehaviorFilters/Behavior.Tips.js,
]
version: Unknown
